{
  "type": "bugfix",
  "category": "pip",
  "description": "Fix RuntimeError with pip v22.x (#1887)"
}
